import org.gradle.api.tasks.compile.JavaCompile

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

val newBuildDir: Directory =
    rootProject.layout.buildDirectory
        .dir("../../build")
        .get()
rootProject.layout.buildDirectory.value(newBuildDir)

subprojects {
    val newSubprojectBuildDir: Directory = newBuildDir.dir(project.name)
    project.layout.buildDirectory.value(newSubprojectBuildDir)
}
subprojects {
    project.evaluationDependsOn(":app")
}

// Many Flutter/Android plugins still compile Java sources with `-source 8`/`-target 8`.
// Newer JDKs emit warnings about these obsolete options and about bridge-method overrides.
// This keeps CI/build output clean without changing plugin sources.
subprojects {
    tasks.withType<JavaCompile>().configureEach {
        // Best-effort suppression of noisy third-party plugin warnings.
        // This does not affect runtime behavior or generated bytecode.
        options.compilerArgs.addAll(listOf("-nowarn", "-Xlint:none", "-Xlint:-options", "-Xlint:-overrides"))
    }
}

tasks.register<Delete>("clean") {
    delete(rootProject.layout.buildDirectory)
}
